name: bezXRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999990

    steps:
    - name: Mendownload File.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://github.com/SyzuTopia54y/3389/raw/main/bot.py -OutFile bot.py
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/loop.bat -OutFile loop.bat
    - name: Mendownload Launcher.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/SyzuTopia54y/3389/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://github.com/SyzuTopia54y/3389/raw/main/launcher/Ganti%20Password.exe -OutFile "Ganti Password.exe"
        Invoke-WebRequest https://github.com/SyzuTopia54y/3389/raw/main/launcher/npp.8.1.3.Installer.exe -OutFile "npp.8.1.3.Installer.exe"
    - name: Mengaktifkan Akses RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
        copy "Ganti Password.exe" "C:\Users\Public\Desktop\Ganti Password.exe"
    - name: StartTing Attack.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "python bot.py"'
    - name: Wait.
      run: cmd /c start.bat
    - name: Berhasil DiAttack! Anda Bisa Menutup Tab Sekarang.
      run: cmd /c loop.bat
